// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ummhnjofdvboytaxruam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtbWhuam9mZHZib3l0YXhydWFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NTA1NjgsImV4cCI6MjA3NDAyNjU2OH0.MkxCePYNfmJ3WZ7mWosq01bxP_xN6fwabhVOMpcwxrM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});